on: push
name: build and test app
jobs:
  build:
    name: install dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: install dependencies
      uses: steebchen/flutter@v1.1.0
      with:
          channel: "stable"
          flutter-version: "3.7.8"
    - run: flutter pub get
      

    - name: flutter build apk
      uses: steebchen/flutter@v1.1.0
      with:
        args: flutter build apk --release
